sudo: false
arch:
  - amd64
  - ppc64le

language: go
go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
  # race and msan are unsupported on 1.9.x and 1.10.x for PPC64LE
    - arch: ppc64le
      go: "1.9.x"
    - arch: ppc64le
      go: "1.10.x"
      
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
